# Generated by Django 5.0.7 on 2024-08-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tiles',
            new_name='shoes',
        ),
    ]
