# Generated by Django 5.0.7 on 2024-08-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_shoes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
