# Generated by Django 5.0.7 on 2024-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_shoes_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.CharField(default='Default Category', max_length=100),
        ),
    ]
