from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]


# Generated by Django 5.0.7 on 2024-08-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_quantity'),
        ('items', '0008_shoes_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shoes',
            new_name='Product',
        ),
    ]
